#both
TOTAL_STOCK_NUM=100
#stockGen.py
GENERATE_STOCK_NAME_LEN_LIMIT=10
#app.py
SINGLE_PAGE_STOCK_NUM=50
ACCOUNT=""
BUTTON_TEXT_10_SPACE='          '
STOCK_PRICE_UPDATE_TIME=10
ROBOT_UPDATE_TIME=1
ROBOT_BUY_PROBABILITY=0.5
ROBOT_SELL_PROBABILITY=1-ROBOT_BUY_PROBABILITY
PRINT_ROBOT_SIGNAL=False
PRINT_STOCK_IMPLICIT_PARAMETER_UPDATE_NUM=False